blank_issues_enabled: false
contact_links:
  - name: Project Documentation
    url: https://config-client.amenezes.net
    about: See if the project documentation or any other issue can help you to solve your doubt or problem before.
